### ISSUE TITLE
Error while processing file, that has imports

### ISSUE THREAD

**Issue by TertiumOrganum1** [ContextMapper/context-mapper-cli#14]
Error while processing file, that has imports (at least local: for example, import "./spa_context.cml")

command:
~/apps/context-mapper-cli-6.12.0/bin/cm generate -i  back_context.cml -g plantuml -o ../out_img
result: 

`Exception in thread "main" java.lang.IllegalArgumentException: resolve against non-hierarchical or relative base
        at org.eclipse.emf.common.util.URI$Hierarchical.resolve(URI.java:3548)
        at org.eclipse.emf.common.util.URI.resolve(URI.java:5580)
        at org.contextmapper.dsl.cml.CMLImportResolver.resolveImportedResources(CMLImportResolver.java:42)
        at org.contextmapper.dsl.cml.CMLModelDomainAndSubdomainResolver.initAllDeclaredSubdomainsIncludingImportedOnes(CMLModelDomainAndSubdomainResolver.java:87)
        at org.contextmapper.dsl.cml.CMLModelDomainAndSubdomainResolver.<init>(CMLModelDomainAndSubdomainResolver.java:38)
        at org.contextmapper.dsl.generator.PlantUMLGenerator.generateFromContextMappingModel(PlantUMLGenerator.java:61)
        at org.contextmapper.dsl.generator.AbstractContextMappingModelGenerator.doGenerate(AbstractContextMappingModelGenerator.java:54)
        at org.contextmapper.dsl.standalone.StandaloneContextMapper.callGenerator(StandaloneContextMapper.java:61)
        at org.contextmapper.cli.commands.GenerateCommand.run(GenerateCommand.java:55)
        at org.contextmapper.cli.ContextMapperCLI.run(ContextMapperCLI.java:59)
        at org.contextmapper.cli.ContextMapperCLI.main(ContextMapperCLI.java:44)`

If there are no imports everything works

**Comment by stefan-ka** [comment]
Hi @toddpi314-reuters 

Yeah, I fear we haven't properly supported the import mechanism in the CLI. I have to find the time to debug and fix this. If anyone could help and create a PR we would of course appreciate it as well ;) Otherwise I'll try my best when the workload allows it.

Best regards,
Stefan
